// <auto-generated />
using System;
using ApiMid.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiMid.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20231205192108_FluentApiConfig")]
    partial class FluentApiConfig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiMid.Models.Midle", b =>
                {
                    b.Property<Guid>("MidleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaRequest")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaResponse")
                        .HasColumnType("datetime2");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MidleID");

                    b.ToTable("Midle", (string)null);

                    b.HasData(
                        new
                        {
                            MidleID = new Guid("93e8d162-ea68-414f-9c33-7c5e2758d79b"),
                            FechaRequest = new DateTime(2023, 12, 5, 14, 21, 8, 297, DateTimeKind.Local).AddTicks(4306),
                            FechaResponse = new DateTime(2023, 12, 5, 14, 21, 8, 297, DateTimeKind.Local).AddTicks(4329),
                            Request = "/programa/algoritmo/solucion/n3urcaVsw4r7,Oscar%20Mejia",
                            Response = "{ result = aV }",
                            Usuario = "Oscar Mejia"
                        },
                        new
                        {
                            MidleID = new Guid("f80f584c-b227-4675-bd1d-9f95c61b4884"),
                            FechaRequest = new DateTime(2023, 12, 5, 14, 21, 8, 297, DateTimeKind.Local).AddTicks(4358),
                            FechaResponse = new DateTime(2023, 12, 5, 14, 21, 8, 297, DateTimeKind.Local).AddTicks(4360),
                            Request = "/programa/algoritmo/solucion/Qc1uoTgfd,Paola%Gutierrez",
                            Response = "{ result = o }",
                            Usuario = "Paola Gutierrez"
                        },
                        new
                        {
                            MidleID = new Guid("37ccf25f-b150-469c-be53-330a2daf86fc"),
                            FechaRequest = new DateTime(2023, 12, 5, 14, 21, 8, 297, DateTimeKind.Local).AddTicks(4366),
                            FechaResponse = new DateTime(2023, 12, 5, 14, 21, 8, 297, DateTimeKind.Local).AddTicks(4368),
                            Request = "/programa/algoritmo/solucion/jafgyA,Ara%20Escobedo",
                            Response = "{ result = fg }",
                            Usuario = "Ara Escobedo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
